In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import ast

In [ ]:
df=pd.read_csv("/content/movies_metadata.csv",engine="python",on_bad_lines="skip")

In [ ]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173

In [ ]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2529 entries, 0 to 2528
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  2529 non-null   bool
 1   belongs_to_collection  430 non-null    object
 2   budget                 2529 non-null   int64
 3   genres                 2529 non-null   object
 4   homepage               153 non-null    object
 5   id                     2529 non-null   int64
 6   imdb_id                2529 non-null   object
 7   original_language      2529 non-null   object
 8   original_title         2529 non-null   object
 9   overview               2511 non-null   object
 10  popularity             2529 non-null   float64
 11  poster_path            2515 non-null   object
 12  production_companies   2529 non-null   object
 13  production_countries   2529 non-null   object
 14  release_date           2527 non-null   object
 15  revenue                2529 non-null   int64
 16  runtime                2523 non-null   float64
 17  spoken_languages       2529 non-null   object
 18  status                 2525 non-null   object
 19  tagline                1934 non-null   object
 20  title                  2529 non-null   object
 21  video                  2529 non-null   bool
 22  vote_average           2529 non-null   float64
 23  vote_count             2529 non-null   int64
dtypes: bool(2), float64(3), int64(4), object(15)
memory usage: 439.7+ KB

In [ ]:
df.shape

(2529, 24)

In [ ]:
df.isnull().sum()

adult                       0
belongs_to_collection    2099
budget                      0
genres                      0
homepage                 2376
id                          0
imdb_id                     0
original_language           0
original_title              0
overview                   18
popularity                  0
poster_path                14
production_companies        0
production_countries        0
release_date                2
revenue                     0
runtime                     6
spoken_languages            0
status                      4
tagline                   595
title                       0
video                       0
vote_average                0
vote_count                  0
dtype: int64

In [ ]:
df=df.drop_duplicates().reset_index(drop=True)

In [ ]:
df.duplicated().sum()

In [ ]:
df=df[["title","overview","genres","tagline","vote_average","popularity"]]

In [ ]:
df.head()

In [ ]:
df=df.dropna(subset=["title"])

In [ ]:
df['overview']=df['overview'].fillna('')

In [ ]:
df.iloc[0]['genres']

In [ ]:
df['genres']=df['genres'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]))

In [ ]:
df.head()

In [ ]:
df['tagline']=df['tagline'].fillna("")

In [ ]:
df.isnull().sum()

In [ ]:
df["tags"]=df['overview']+" "+df['genres']+" "+df['tagline']

In [ ]:
df.head(

)

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [ ]:
df['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family "

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [ ]:
def preprocess_text(text):
    #lowercase
    text=text.lower()
    #remove the punctuation
    text=re.sub(r'[^a-zA-Z0-9\s]','',text)

    words=text.split()
    #REMOVE STOPWORDS
    words=[word for word in words if word not in stop_words]

    #lemmatization
    words=[lemmatizer.lemmatize(word)for word in words ]
    return " ".join(words)

In [ ]:
df['tags']=df['tags'].apply(preprocess_text)

In [ ]:
df=df.reset_index(drop=True)

In [ ]:
indices=pd.Series(df.index,index=df['title']).drop_duplicates()
indices

title
Toy Story                         0
Jumanji                           1
Grumpier Old Men                  2
Waiting to Exhale                 3
Father of the Bride Part II       4
                               ...
The Mummy's Tomb               2523
Mommie Dearest                 2524
Superman                       2525
Superman II                    2526
Superman III                   2527
Length: 2528, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf=TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [ ]:
tfidf_matrix=tfidf.fit_transform(df['tags'])

In [ ]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 123314 stored elements and shape (2528, 50000)>

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
def recommend(title,n=10):
    if title not in indices:
        return ["Movie not found"]
    idx=indices[title]
    sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx=sim_score.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx]

In [ ]:
recommend('Malice')

0                Toy Story
1127              Dear God
1008     The Lawnmower Man
2095      Mr. & Mrs. Smith
2317           Patch Adams
959                  Bliss
1177    The Blues Brothers
1454          Commandments
164          Feast of July
54                 Georgia
Name: title, dtype: object

In [ ]:
import pickle
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open ('tfidf.pkl','wb'))